# Generated by Django 3.0.6 on 2020-05-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200529_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku_code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
